// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// ORTHOG
arma::mat ORTHOG(arma::mat& X, arma::mat& Y, arma::mat& T, int xm, int xn, int yn);
RcppExport SEXP _ExampleIRLBA_ORTHOG(SEXP XSEXP, SEXP YSEXP, SEXP TSEXP, SEXP xmSEXP, SEXP xnSEXP, SEXP ynSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type T(TSEXP);
    Rcpp::traits::input_parameter< int >::type xm(xmSEXP);
    Rcpp::traits::input_parameter< int >::type xn(xnSEXP);
    Rcpp::traits::input_parameter< int >::type yn(ynSEXP);
    rcpp_result_gen = Rcpp::wrap(ORTHOG(X, Y, T, xm, xn, yn));
    return rcpp_result_gen;
END_RCPP
}
// IRLB
List IRLB(arma::mat& X, int nu, int work, int maxit, double tol, double eps, double svtol);
RcppExport SEXP _ExampleIRLBA_IRLB(SEXP XSEXP, SEXP nuSEXP, SEXP workSEXP, SEXP maxitSEXP, SEXP tolSEXP, SEXP epsSEXP, SEXP svtolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< int >::type nu(nuSEXP);
    Rcpp::traits::input_parameter< int >::type work(workSEXP);
    Rcpp::traits::input_parameter< int >::type maxit(maxitSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    Rcpp::traits::input_parameter< double >::type svtol(svtolSEXP);
    rcpp_result_gen = Rcpp::wrap(IRLB(X, nu, work, maxit, tol, eps, svtol));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_ExampleIRLBA_ORTHOG", (DL_FUNC) &_ExampleIRLBA_ORTHOG, 6},
    {"_ExampleIRLBA_IRLB", (DL_FUNC) &_ExampleIRLBA_IRLB, 7},
    {NULL, NULL, 0}
};

RcppExport void R_init_ExampleIRLBA(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
