# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ORTHOG <- function(X, Y, T, xm, xn, yn) {
    .Call(`_ExampleIRLBA_ORTHOG`, X, Y, T, xm, xn, yn)
}

IRLB <- function(X, nu, work, maxit = 1000L, tol = 1e-5, eps = 1e-9, svtol = 1e-5) {
    .Call(`_ExampleIRLBA_IRLB`, X, nu, work, maxit, tol, eps, svtol)
}

